[book]
authors = ["Yuji Nagaoka"]
language = "ja"
multilingual = false
src = "docs"
title = "notebook"

[preprocessor.katex]

[output.html]
no-section-label = true
git-repository-url = "https://github.com/nagaokayuji/competitive-programming"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2